import {test,expect} from '@playwright/test';import {qa,saveQa} from '../../scripts/qa-state';
test('owner bootstrap, login, projects, real reference ingestion, failures, checkout, releases and mobile',async({page,context})=>{
 await page.goto('/login');
 await expect(page.getByRole('button',{name:/Create owner|Sign in/})).toBeEnabled();
 if(await page.getByRole('heading',{name:'Set up your installation'}).isVisible()){
  await page.getByLabel('Setup token').fill(process.env.SETUP_TOKEN!);await page.getByLabel('Your name').fill('Local verification owner');await page.getByLabel('Email',{exact:true}).fill(qa.email);await page.getByLabel('Password',{exact:true}).fill(qa.password);await page.getByRole('button',{name:'Create owner'}).click();await expect(page.getByRole('heading',{name:'Welcome back'})).toBeVisible();
 }
 await page.getByLabel('Email',{exact:true}).fill(qa.email);await page.getByLabel('Password',{exact:true}).fill(qa.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Overview',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Setup',exact:true}).click();
 const create=page.locator('section').filter({has:page.getByRole('heading',{name:'Create a project',exact:true})});
 await create.getByLabel('Project name',{exact:true}).fill('Reference storefront');await create.getByRole('button',{name:'Create project',exact:true}).click();await expect(page.getByRole('status')).toContainText('Project created');
 const response=await context.request.get('/api/projects');const ps=await response.json();const p=ps.at(-1);qa.referenceId=p.id;qa.referenceIngestionId=p.ingestionId;saveQa();
 await page.getByRole('combobox',{name:'Project',exact:true}).selectOption(p.id);
 const ref=await context.newPage();await ref.goto('http://localhost:3001');await ref.getByLabel('Public ingestion identifier').fill(p.ingestionId);await ref.getByRole('button',{name:'Connect reference project'}).click();await expect(ref.getByRole('status')).toContainText('Reference project connected');
 await ref.getByRole('combobox',{name:'Deterministic scenario'}).selectOption('failure');await ref.getByRole('button',{name:'Test check_delivery'}).click();await expect(ref.getByRole('status')).toContainText('failure (manual)');await expect(ref.getByRole('button',{name:'Test check_delivery'})).toBeEnabled();
 await ref.getByRole('combobox',{name:'Deterministic scenario'}).selectOption('success');await ref.getByRole('button',{name:'Test search_products'}).click();await expect(ref.getByRole('button',{name:'Test search_products'})).toBeEnabled();await ref.getByRole('button',{name:'Test add_to_cart'}).click();await expect(ref.getByRole('button',{name:'Save simulated order'})).toBeEnabled();await ref.getByRole('button',{name:'Save simulated order'}).click();await expect(ref.getByRole('status')).toContainText('Simulated order saved');
 await ref.getByRole('combobox',{name:'Deterministic scenario'}).selectOption('slow');await ref.getByRole('button',{name:'Test check_delivery'}).click();await expect(ref.getByRole('button',{name:'Test check_delivery'})).toBeEnabled();
 await ref.getByRole('combobox',{name:'Deterministic scenario'}).selectOption('cancellation');await ref.getByRole('button',{name:'Test check_delivery'}).click();await ref.getByRole('button',{name:'Cancel execution'}).click();await expect(ref.getByRole('status')).toContainText('cancellation (manual)');await expect(ref.getByRole('button',{name:'Test check_delivery'})).toBeEnabled();
 await ref.getByRole('combobox',{name:'Application release'}).selectOption('v2');await ref.getByRole('button',{name:'Connect reference project'}).click();await ref.getByRole('combobox',{name:'Deterministic scenario'}).selectOption('failure');await ref.getByRole('button',{name:'Test check_delivery'}).click();await expect(ref.getByRole('status')).toContainText('success (manual)');await expect(ref.getByRole('button',{name:'Test check_delivery'})).toBeEnabled();
 await page.getByRole('button',{name:'Overview',exact:true}).click();await page.getByRole('button',{name:'Refresh',exact:true}).click();await expect(page.getByText('DELIVERY_UNAVAILABLE',{exact:false})).toHaveCount(0);await expect(page.getByRole('button',{name:'check_delivery',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Tools',exact:true}).click();await expect(page.getByText('check_delivery / DELIVERY_UNAVAILABLE')).toBeVisible();await expect(page.getByRole('cell',{name:'v1',exact:true})).toBeVisible();await expect(page.getByRole('cell',{name:'v2',exact:true})).toBeVisible();await page.getByRole('button',{name:'Compare previous equal-length period'}).click();await expect(page.getByText('Previous:',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Workflow',exact:true}).click();await expect(page.getByRole('heading',{name:'Correlated execution timeline'})).toBeVisible();await expect(page.locator('summary').first()).toBeVisible();
 await page.getByRole('button',{name:'Overview',exact:true}).click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'work/dashboard-desktop.png',fullPage:true,animations:'disabled'});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'work/dashboard-mobile.png',fullPage:true,animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await ref.reload();await expect(ref.getByText('1 simulated orders saved',{exact:true})).toBeVisible();await ref.close();
});
