'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {BarChart3,Wrench,Workflow,Settings,RefreshCw,LogOut,ArrowDownToLine,Activity} from 'lucide-react';
import {LineChart,Line,CartesianGrid,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import {registerTools,reportFilterSchema,type AnalyticsReport,type ReportFilter,type BrowserTool} from '@tally-local/shared';
import Setup from './setup';
export type Project={id:string;name:string;ingestionId:string;origins:string[];tools:string[];environments:string[];releases:string[];errorCodes:string[];routeLabels:string[];workflowName:string;retentionDays:number;dailyQuota:number};
export const ms=(n:number|null)=>n===null?'—':`${Math.round(n).toLocaleString()} ms`;
const pct=(n:number|null)=>n===null?'—':`${(100*n).toFixed(1).replace('.0','')}%`;
export async function api<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,init);if(r.status===401){window.location.assign('/login');throw Error('Session expired');}const d=await r.json();if(!r.ok)throw Error(d.error??'Request failed');return d;}
function query(f:ReportFilter){return new URLSearchParams(Object.entries(f).filter(([,v])=>v!==undefined) as [string,string][]).toString();}
export default function Dashboard(){
 const [page,setPage]=useState('Overview'),[projects,setProjects]=useState<Project[]>([]),[projectId,setProject]=useState(''),[environment,setEnvironment]=useState(''),[source,setSource]=useState(''),[tool,setTool]=useState(''),[release,setRelease]=useState(''),[days,setDays]=useState('7'),[anchor,setAnchor]=useState(()=>new Date().toISOString()),[custom,setCustom]=useState<{from:string;to:string}|null>(null),[report,setReport]=useState<AnalyticsReport|null>(null),[previous,setPrevious]=useState<AnalyticsReport|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[native,setNative]=useState('Checking native WebMCP support…'),[search,setSearch]=useState('');
 const project=projects.find(p=>p.id===projectId);
 const refreshProjects=useCallback(async()=>{const ps=await api<Project[]>('/api/projects');setProjects(ps);setProject(current=>ps.some(p=>p.id===current)?current:ps[0]?.id??'');setLoading(false);},[]);
 useEffect(()=>{void refreshProjects().catch(e=>{setError(e.message);setLoading(false);});},[refreshProjects]);
 const filters=useMemo<ReportFilter>(()=>({projectId,from:custom?.from??new Date(Date.parse(anchor)-Number(days)*86400000).toISOString(),to:custom?.to??anchor,...(environment?{environment}:{}),...(source?{source:source as ReportFilter['source']}:{}),...(tool?{tool}:{}),...(release?{release}:{})}),[projectId,anchor,days,environment,source,tool,release,custom]);
 useEffect(()=>{if(!projectId)return;const ac=new AbortController();setLoading(true);setError('');setReport(null);setPrevious(null);api<AnalyticsReport>('/api/reports?'+query(filters),{signal:ac.signal}).then(setReport).catch(e=>{if(!ac.signal.aborted)setError(e.message);}).finally(()=>{if(!ac.signal.aborted)setLoading(false);});return()=>ac.abort();},[filters,projectId]);
 useEffect(()=>{const ac=new AbortController();if(!projectId)return;
  const inputSchema={type:'object',properties:{projectId:{type:'string',format:'uuid'},from:{type:'string',format:'date-time'},to:{type:'string',format:'date-time'},environment:{type:'string',maxLength:64},source:{type:'string',enum:['webmcp','manual','application','unknown']},tool:{type:'string',maxLength:64},release:{type:'string',maxLength:64}},required:['projectId','from','to'],additionalProperties:false};
  const run=async(input:unknown)=>{const f=reportFilterSchema.parse(input);return api<AnalyticsReport>('/api/reports?'+query(f));};
  const tools:BrowserTool[]=[{name:'get_tool_metrics',description:'Read bounded application-reported tool metrics for an authorized project. UTC range max 31 days.',inputSchema,annotations:{readOnlyHint:true},execute:run},{name:'get_tool_failures',description:'Read normalized failure groups with definitions, sample size and freshness.',inputSchema,annotations:{readOnlyHint:true},async execute(input:unknown){const r=await run(input);return {definitions:r.definitions,period:r.period,filters:r.filters,sampleSize:r.sampleSize,freshness:r.freshness,failures:r.failures};}},{name:'set_dashboard_filters',description:'Validate project access and visibly apply dashboard filters.',inputSchema,async execute(input:unknown){const f=reportFilterSchema.parse(input);const r=await run(f);setProject(f.projectId);setEnvironment(f.environment??'');setSource(f.source??'');setTool(f.tool??'');setRelease(f.release??'');setCustom({from:f.from,to:f.to});return {applied:f,period:r.period,sampleSize:r.sampleSize,definitions:r.definitions,freshness:r.freshness};}}];
  void registerTools(tools,ac.signal).then(s=>{if(!ac.signal.aborted)setNative(s);});return()=>ac.abort();
 },[projectId]);
 async function compare(){try{const length=Date.parse(filters.to)-Date.parse(filters.from);setPrevious(await api<AnalyticsReport>('/api/reports?'+query({...filters,from:new Date(Date.parse(filters.from)-length).toISOString(),to:filters.from})));}catch(e){setError((e as Error).message);}}
 const summary=report?.summary;
 const rows=report?.tools.filter(t=>t.tool.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.failure-a.failure)??[];
 return <div className="shell"><aside className="rail"><a className="brand" href="/"><svg className="mark" width="32" height="34" viewBox="0 0 32 34" aria-hidden="true"><path d="M6 5v24M13 5v24M20 5v24M27 5v24M2 26L31 9" stroke="currentColor" strokeWidth="2.5" fill="none" strokeLinecap="round"/></svg>Tally</a><nav aria-label="Main navigation">{[[BarChart3,'Overview'],[Wrench,'Tools'],[Workflow,'Workflow'],[Settings,'Setup']].map(([Icon,label])=>{const I=Icon as typeof Activity;return <button key={String(label)} aria-current={page===label?'page':undefined} className={page===label?'selected':''} onClick={()=>setPage(String(label))}><I size={21}/>{String(label)}</button>;})}</nav><div className="rail-bottom"><button onClick={async()=>{try{await api('/api/auth/sign-out',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});window.location.assign('/login');}catch(e){setError((e as Error).message);}}}><LogOut size={18}/>Sign out</button><p>Every agent action counts.</p></div></aside><div className="workspace"><header className="toolbar"><label>Project<select value={projectId} onChange={e=>{setProject(e.target.value);setEnvironment('');setTool('');setRelease('');}}><option value="" disabled>Select a project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Environment<select value={environment} onChange={e=>setEnvironment(e.target.value)}><option value="">All environments</option>{project?.environments.map(v=><option key={v}>{v}</option>)}</select></label><label>Date range<select value={custom?'custom':days} onChange={e=>{setCustom(null);setDays(e.target.value);setAnchor(new Date().toISOString());}}>{custom&&<option value="custom">Custom range</option>}<option value="1">Last 24 hours</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select></label><button onClick={()=>setAnchor(new Date().toISOString())}><RefreshCw size={17}/>Refresh</button></header><main id="main"><div className="page-heading"><div><h1>{page}</h1><p className="muted">Application-reported tool activity.</p></div><span className="freshness">{report?.freshness?`Last received ${new Date(report.freshness).toLocaleString()}`:'No events received'}</span></div>{error&&<div role="alert" className="notice error">{error}<button onClick={()=>setAnchor(new Date().toISOString())}>Retry</button></div>}
 {page==='Setup'?<Setup projects={projects} project={project} onChange={refreshProjects} firstEvent={report?.freshness??null}/>:!projectId&&!loading?<section className="panel empty"><Activity size={36}/><h2>Start counting your agent actions</h2><p>Create a project, install the SDK, and run your first instrumented tool.</p><button className="primary" onClick={()=>setPage('Setup')}>Create a project</button></section>:loading?<section className="panel" role="status">Loading stored observations…</section>:report&&summary?<>
 <div className="filter-row"><label>Execution source<select value={source} onChange={e=>setSource(e.target.value)}><option value="">All reported sources</option>{['webmcp','manual','application','unknown'].map(s=><option key={s}>{s}</option>)}</select></label><label>Tool<select value={tool} onChange={e=>setTool(e.target.value)}><option value="">All tools</option>{project?.tools.map(s=><option key={s}>{s}</option>)}</select></label><label>Release<select value={release} onChange={e=>setRelease(e.target.value)}><option value="">All releases</option>{project?.releases.map(s=><option key={s}>{s}</option>)}</select></label><a className="button" href={'/api/reports?'+query(filters)+'&export=json'}><ArrowDownToLine size={16}/>Export JSON</a></div>
 <p className="period">{filters.from} → {filters.to} · UTC · End exclusive</p>
 {page!=='Workflow'&&<section className="summary-strip"><Metric label="Calls started" value={summary.callsStarted}/><Metric label="Success rate" value={pct(summary.successRate)} good detail={`${summary.success} successes / ${summary.failure} failures`}/><Metric label="Median latency" value={ms(summary.medianMs)}/><Metric label="p95 latency" value={ms(summary.p95Ms)} detail={`${summary.latencySamples} latency samples`}/><div><p className="muted">Excluded from success rate</p><p><b>{summary.cancellation}</b> cancellation</p><p><b>{summary.incomplete}</b> incomplete</p><p><b>{summary.unknown}</b> unknown / conflicted</p></div></section>}
 {report.sampleSize===0&&page!=='Workflow'&&<p className="notice">No observed starts in this period. Run an instrumented tool, check Setup, or adjust your filters. Unavailable rates and latency display as —.</p>}
 {page==='Overview'&&<div className="chart-grid"><section className="panel"><h2>Tool activity trend</h2><p className="muted">Observed starts and failures by daily UTC cohort</p><div role="img" aria-label={`Daily activity chart. ${summary.callsStarted} starts and ${summary.failure} failures. Data available in the following table.`} className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={report.trend}><CartesianGrid stroke="#e1e8ee" vertical={false}/><XAxis dataKey="date" tickFormatter={s=>new Date(s).toLocaleDateString(undefined,{month:'short',day:'numeric',timeZone:'UTC'})} minTickGap={25}/><YAxis allowDecimals={false} width={35}/><Tooltip labelFormatter={s=>String(s)}/><Line isAnimationActive={false} name="Calls started" dataKey="calls" stroke="#12855f" strokeWidth={2} dot={false}/><Line isAnimationActive={false} name="Failures" dataKey="failures" stroke="#dc4d4d" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div><details><summary>View chart data</summary><table><thead><tr><th>UTC bucket start</th><th>Calls</th><th>Failures</th></tr></thead><tbody>{report.trend.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.calls}</td><td>{d.failures}</td></tr>)}</tbody></table></details></section><section className="panel"><h2>Tool call outcomes</h2>{(['success','failure','cancellation','incomplete','unknown'] as const).map(k=><div className="outcome" key={k}><span><i className={'dot '+k}/>{k[0].toUpperCase()+k.slice(1)}</span><b>{summary[k]}</b></div>)}<p className="muted">{report.missingStarts.count} records missing a start, shown separately.</p></section></div>}
 {(page==='Tools'||page==='Overview')&&<section className="panel table-panel"><div className="section-heading"><h2>{page==='Overview'?'Frequently failing tools':'Instrumented tools'}</h2><label className="search">Search tools<input aria-label="Search tools" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a tool…"/></label></div><div className="table-scroll"><table><thead><tr><th>Tool name</th><th>Calls</th><th>Failures</th><th>Success rate</th><th>Median latency</th><th>p95 latency</th></tr></thead><tbody>{rows.map(r=><tr key={r.tool}><td><button className="text-button mono" onClick={()=>{setTool(r.tool);setPage('Tools');}}>{r.tool}</button></td><td>{r.callsStarted}</td><td className={r.failure?'bad':''}>{r.failure}</td><td>{pct(r.successRate)}</td><td>{ms(r.medianMs)}</td><td>{ms(r.p95Ms)}</td></tr>)}</tbody></table>{!rows.length&&<p className="empty">No matching tools in this period.</p>}</div></section>}
 {page==='Tools'&&<><section className="panel"><h2>Normalized error groups</h2>{report.failures.length?report.failures.map(g=><div className="outcome" key={g.group}><code>{g.group}</code><b>{g.count}</b></div>):<p className="muted">No unambiguous failures in this cohort.</p>}</section><section className="panel table-panel"><h2>Release comparison</h2><p className="muted">Observed differences do not establish that a release caused the change.</p><div className="table-scroll"><table><thead><tr><th>Release</th><th>First / last observed start (UTC)</th><th>Calls</th><th>Success rate</th><th>p95 / samples</th></tr></thead><tbody>{report.releases.map(r=><tr key={r.release}><td><code>{r.release}</code></td><td>{r.first}<br/>{r.last}</td><td>{r.callsStarted}</td><td>{pct(r.successRate)}</td><td>{ms(r.p95Ms)} / {r.latencySamples}</td></tr>)}</tbody></table></div><button onClick={compare}>Compare previous equal-length period</button>{previous&&<div className="notice"><p>Previous: {previous.period.from} → {previous.period.to}</p><p>{previous.sampleSize} calls · {pct(previous.summary.successRate)} success · {ms(previous.summary.p95Ms)} p95 ({previous.summary.latencySamples} samples)</p><p>Current: {report.sampleSize} calls · {pct(summary.successRate)} success · {ms(summary.p95Ms)} p95 ({summary.latencySamples} samples)</p></div>}</section><Records title="Recent sanitized invocations" records={report.recent}/><Records title={`Missing-start records (${report.missingStarts.count})`} records={report.missingStarts.records}/></>}
 {page==='Workflow'&&<><h2>{project?.workflowName} · Observed workflow completion</h2><p className="muted">30-minute observation window. Newer starts remain open, including early completions. {report.workflow.filterNote}</p><section className="summary-strip"><Metric label="Matured starts" value={report.workflow.matured}/><Metric label="Completions in window" value={report.workflow.completed}/><Metric label="Observed completion" value={pct(report.workflow.rate)} good/><Metric label="Open workflows" value={report.workflow.open}/></section><p className="notice">{report.workflow.missingCompletion} missing completion after the window · {report.workflow.missingStarts} completions missing a start · {report.workflow.conflicted} conflicted workflows</p><section className="panel"><h2>Correlated execution timeline</h2>{!report.workflow.timeline.length&&<p>No workflow starts in this period. Record a new task instance in your application.</p>}{report.workflow.timeline.map(w=><details key={w.id}><summary><code>{w.id.slice(0,8)}</code> · {w.status} · {w.start}</summary><p>Definition {w.name} v{w.version} · {w.windowMs/60000}-minute window</p>{w.executions.map(e=><p key={e.id}><code>{e.tool}</code> → {e.outcome} · {ms(e.durationMs)}</p>)}</details>)}</section></>}
 </>:null}<section className="native-status"><Activity size={18}/><p>{native}</p></section></main></div></div>;
}
function Metric({label,value,detail,good}:{label:string;value:string|number;detail?:string;good?:boolean}){return <div><p className="muted">{label}</p><strong className={good?'good':''}>{value}</strong>{detail&&<p className="metric-detail">{detail}</p>}</div>;}
function Records({title,records}:{title:string;records:AnalyticsReport['recent']}){return <section className="panel table-panel"><h2>{title}</h2><div className="table-scroll"><table><thead><tr><th>Invocation</th><th>Tool</th><th>Start (UTC)</th><th>Outcome</th><th>Duration</th><th>Source</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td><code title={r.id}>{r.id.slice(0,8)}</code></td><td><code>{r.tool}</code></td><td>{r.start??'Missing start'}</td><td>{r.outcome}</td><td>{ms(r.durationMs)}</td><td>{r.source}</td></tr>)}</tbody></table>{!records.length&&<p className="empty">No records to show.</p>}</div></section>;}
