import {describe,it,expect,vi} from 'vitest';import {createTallyClient,type Config} from '../packages/sdk/src';
const base:Config={endpoint:'http://localhost:3000/api/v1/events',ingestionId:crypto.randomUUID(),environment:'test',allowedMetadata:{tools:['test'],errorCodes:['DELIVERY_UNAVAILABLE'],workflowNames:['checkout']},flushIntervalMs:30000};
function setup(extra:Partial<Config>={}){const events:any[]=[];const fetch=vi.fn(async(_url:any,init:any)=>{events.push(...JSON.parse(init.body).events);return new Response('{}',{status:202});});return {events,fetch,t:createTallyClient({...base,fetch,...extra})};}
describe('SDK contract',()=>{
 it('preserves exactly one sync call, this, metadata, arguments and result without sensitive payloads',async()=>{const {t,events}=setup();const result={secret:'private result'};const context={signal:new AbortController().signal};const action=vi.fn(function(this:any,arg:any,ctx:any){expect(this.marker).toBe(1);expect(arg.secret).toBe('private input');expect(ctx).toBe(context);return result;});const tool=t.wrapTool({name:'test',description:'preserved',inputSchema:{type:'object'},execute:action},{source:'manual'});expect(tool.execute.call({marker:1},{secret:'private input'},context)).toBe(result);expect(action).toHaveBeenCalledTimes(1);expect(tool.description).toBe('preserved');await t.flush();expect(events.map(e=>e.kind)).toEqual(['tool_started','tool_finished']);expect(JSON.stringify(events)).not.toMatch(/private input|private result|secret|signal/);t.disable();});
 it('rethrows original sync and async errors, classifies structured errors',async()=>{const {t,events}=setup();const e=Object.assign(new Error('do not record'),{code:'DELIVERY_UNAVAILABLE'});expect(()=>t.wrapTool({name:'test',execute(){throw e;}},{source:'webmcp'}).execute()).toThrow(e);await expect(t.wrapTool({name:'test',async execute(){throw e;}},{source:'webmcp'}).execute()).rejects.toBe(e);const r={isError:true,content:[{text:'secret'}]};expect(t.wrapTool({name:'test',execute:()=>r},{source:'manual'}).execute()).toBe(r);await t.flush();expect(events.filter(e=>e.kind==='tool_finished').map(e=>e.outcome)).toEqual(['failure','failure','failure']);expect(JSON.stringify(events)).not.toContain('do not record');t.disable();});
 it('observes cancellation rejection but does not infer cancellation from an aborted signal alone',async()=>{const {t,events}=setup();const ac=new AbortController();ac.abort();const e=new DOMException('private','AbortError');await expect(t.wrapTool({name:'test',async execute(_a:any,c:any){expect(c.signal).toBe(ac.signal);throw e;}},{source:'manual'}).execute({}, {signal:ac.signal})).rejects.toBe(e);expect(t.wrapTool({name:'test',execute:(_args:unknown,_ctx:unknown)=>42},{source:'manual'}).execute({}, {signal:ac.signal})).toBe(42);await t.flush();expect(events.filter(e=>e.outcome).map(e=>e.outcome)).toEqual(['cancellation','success']);t.disable();});
 it('classifier errors produce unknown without changing the result',async()=>{const {t,events}=setup();const r={ok:true};expect(t.wrapTool({name:'test',execute:()=>r},{source:'manual',classifyResult:()=>{throw Error('secret');}}).execute()).toBe(r);await t.flush();expect(events.at(-1).outcome).toBe('unknown');expect(t.getDiagnostics().classifierErrors).toBe(1);t.disable();});
 it('bounds overflow, batches and permanent rejections',async()=>{const {t,fetch}=setup({maxBuffer:3,batchSize:2,fetch:vi.fn(async()=>new Response('{}',{status:400}))});const action=t.wrapTool({name:'test',execute:()=>1},{source:'manual'});for(let i=0;i<5;i++)action.execute();expect(t.getDiagnostics().queued).toBe(3);expect(t.getDiagnostics().dropped).toBe(7);await t.flush();expect(t.getDiagnostics().rejected).toBe(3);expect(fetch).not.toHaveBeenCalled();t.disable();});
 it('outages and timeouts are finite even with an uncooperative transport',async()=>{const fetch=vi.fn(()=>new Promise<Response>(()=>{}));const {t}=setup({fetch,timeoutMs:10,maxRetries:1});expect(t.wrapTool({name:'test',execute:()=>7},{source:'manual'}).execute()).toBe(7);await t.flush();expect(fetch).toHaveBeenCalledTimes(2);expect(t.getDiagnostics().dropped).toBe(2);t.disable();});
 it('disabled collection discards the queue and sends nothing',async()=>{const {t,fetch}=setup();t.wrapTool({name:'test',execute:()=>1},{source:'manual'}).execute();t.disable();await t.flush();t.wrapTool({name:'test',execute:()=>1},{source:'manual'}).execute();expect(fetch).not.toHaveBeenCalled();expect(t.getDiagnostics().queued).toBe(0);});
 it('retries transient failures and enforces maximum batch size',async()=>{let attempts=0;const fetch=vi.fn(async(_u:any,i:any)=>{expect(JSON.parse(i.body).events.length).toBeLessThanOrEqual(2);return new Response('{}',{status:++attempts===1?503:202});});const {t}=setup({fetch,batchSize:2,maxRetries:1});for(let i=0;i<3;i++)t.wrapTool({name:'test',execute:()=>1},{source:'manual'}).execute();await t.flush();expect(fetch).toHaveBeenCalledTimes(4);t.disable();});
});
