import './env';import {qa,saveQa} from './qa-state';import {mkdirSync,writeFileSync,copyFileSync} from 'node:fs';import {resolve,join} from 'node:path';import {spawnSync} from 'node:child_process';import assert from 'node:assert/strict';
// A sibling of outputs/, outside this pnpm workspace and its dependency graph.
const dir=resolve('../../work/independent-consumer');mkdirSync(dir,{recursive:true});mkdirSync('artifacts',{recursive:true});
function run(args:string[],cwd=process.cwd()){const r=spawnSync(process.platform==='win32'?'pnpm.cmd':'pnpm',args,{cwd,encoding:'utf8',shell:process.platform==='win32',env:{...process.env},maxBuffer:10*1024*1024});if(r.status!==0)throw Error(r.stdout+'\n'+r.stderr);return r.stdout;}
async function main(){run(['--filter','@tally-local/sdk','build']);run(['--filter','@tally-local/sdk','pack','--pack-destination',resolve('artifacts')]);const archive='tally-local-sdk-0.1.0.tgz';copyFileSync(join('artifacts',archive),join(dir,archive));
 writeFileSync(join(dir,'package.json'),JSON.stringify({name:'independent-tally-consumer',private:true,type:'module',scripts:{test:'node index.mjs'},dependencies:{'@tally-local/sdk':'file:./'+archive},devDependencies:{typescript:'5.9.3'}}));
 writeFileSync(join(dir,'tsconfig.json'),JSON.stringify({compilerOptions:{strict:true,noEmit:true,target:'ES2022',module:'NodeNext',moduleResolution:'NodeNext',lib:['ES2022','DOM']},include:['consumer.ts']}));
 writeFileSync(join(dir,'consumer.ts'),`import {createTallyClient,type Config} from '@tally-local/sdk';\nconst config:Config={endpoint:'http://localhost:3000/api/v1/events',ingestionId:crypto.randomUUID(),environment:'test',allowedMetadata:{tools:['test'],errorCodes:[],workflowNames:['checkout']}};\nconst t=createTallyClient(config);const value:number=t.wrapTool({name:'test',execute:(n:number)=>n+1},{source:'manual'}).execute(3);t.disable();\n`);
 writeFileSync(join(dir,'index.mjs'),`import assert from 'node:assert/strict';import {createTallyClient} from '@tally-local/sdk';\nlet calls=0;const t=createTallyClient({endpoint:'http://localhost:3000/api/v1/events',ingestionId:process.env.TALLY_QA_INGESTION,environment:'test',release:'v2',allowedMetadata:{tools:['test'],errorCodes:[],workflowNames:['checkout']},fetch:(url,init)=>fetch(url,{...init,headers:{...init.headers,Origin:'http://localhost:3001'}})});\nconst result={private:'not transmitted'};assert.equal(t.wrapTool({name:'test',execute:()=>{calls++;return result;}},{source:'manual'}).execute(),result);assert.equal(calls,1);await t.flush();assert.equal(t.getDiagnostics().dropped,0);assert.equal(t.getDiagnostics().rejected,0);t.disable();console.log('Independent ESM archive import, real ingestion, and callback preservation passed');\n`);
 run(['install','--ignore-workspace'],dir);run(['exec','tsc','--noEmit'],dir);process.env.TALLY_QA_INGESTION=qa.ingestionId;const output=run(['test'],dir);assert.match(output,/passed/);console.log(output.trim());writeFileSync('work/independent-results.json',JSON.stringify({checkedAt:new Date().toISOString(),archive,checks:['Archive installed outside workspace graph','TypeScript declarations compiled','ESM consumer callback ran once','Real HTTP ingestion accepted'],output:output.trim()},null,2));saveQa();
}
main().catch(e=>{console.error(e);process.exitCode=1;});
