import './env';import {qa,saveQa} from './qa-state';import {PrismaClient} from '@prisma/client';import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';
const db=new PrismaClient({log:[]}),base='http://localhost:3000',origin=base;let cookie='';const results:string[]=[];
async function http(path:string,body?:unknown,opts:{anon?:boolean;origin?:string;headers?:Record<string,string>}={}){return fetch(base+path,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{'Content-Type':'application/json',Origin:opts.origin??origin}),...(!opts.anon?{Cookie:cookie}:{}),...opts.headers},body:body===undefined?undefined:typeof body==='string'?body:JSON.stringify(body)});}
function checked(name:string){results.push(name);console.log('PASS '+name);}
const definition={name:'Backend verification',origins:['http://localhost:3001'],tools:['test'],environments:['test'],releases:['v1','v2'],errorCodes:['DELIVERY_UNAVAILABLE'],routeLabels:[],workflowName:'checkout',retentionDays:30,dailyQuota:100000};
const event=(kind:string,id:string,extra:Record<string,unknown>={})=>({schemaVersion:1,eventId:crypto.randomUUID(),kind,invocationId:id,tool:'test',environment:'test',release:'v1',source:'manual',clientAt:new Date().toISOString(),...extra});
async function main(){
 const login=await http('/api/auth/sign-in/email',{email:qa.email,password:qa.password},{anon:true});assert.equal(login.status,200,'login');cookie=login.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ');assert.ok(cookie);checked('owner login issues session cookie');
 const pRes=await http('/api/projects',definition);assert.equal(pRes.status,201);const p=await pRes.json();qa.projectId=p.id;qa.ingestionId=p.ingestionId;saveQa();
 const batch=async(events:unknown[],id=p.ingestionId,orig='http://localhost:3001')=>http('/api/v1/events',{ingestionId:id,events},{anon:true,origin:orig});
 const ids=Array.from({length:10},()=>crypto.randomUUID());const starts=ids.map(id=>event('tool_started',id));const ends=ids.slice(0,9).map((id,i)=>event('tool_finished',id,{outcome:i<6?'success':i<8?'failure':'cancellation',durationMs:(i+1)*100}));
 assert.equal((await batch(ends)).status,202);assert.equal((await batch(starts)).status,202);const duplicates=await Promise.all(Array.from({length:10},()=>batch([...starts,...ends])));assert.ok(duplicates.every(r=>r.status===202));assert.equal(await db.event.count({where:{projectId:p.id}}),19);checked('out-of-order and 10 concurrent duplicate batches persist once');
 const f=new URLSearchParams({projectId:p.id,from:new Date(Date.now()-86400000).toISOString(),to:new Date(Date.now()+1000).toISOString()});const r=await (await http('/api/reports?'+f)).json();assert.equal(r.summary.successRate,.75);assert.equal(r.summary.medianMs,450);assert.equal(r.summary.p95Ms,800);assert.equal(r.summary.incomplete,1);checked('persisted 10-start fixture produces 75%, median 450ms, p95 800ms');
 assert.equal((await http('/api/reports?'+f,undefined,{anon:true,headers:{Authorization:'Bearer '+p.ingestionId}})).status,401);assert.equal((await http('/api/projects',undefined,{anon:true})).status,401);assert.equal((await http('/api/projects',definition,{origin:'https://untrusted.invalid'})).status,403);const other=new URLSearchParams(f);other.set('projectId',crypto.randomUUID());assert.equal((await http('/api/reports?'+other)).status,404);checked('ingestion IDs cannot read; unauthenticated and cross-origin owner actions rejected');
 assert.equal((await batch([{...starts[0],secret:'must reject'}])).status,400);assert.equal((await batch([{...starts[0],schemaVersion:2}])).status,400);assert.equal((await batch(Array(51).fill(starts[0]))).status,400);assert.equal((await batch(starts,p.ingestionId,'https://untrusted.invalid')).status,403);assert.equal((await http('/api/v1/events','x'.repeat(65537),{anon:true,origin:'http://localhost:3001'})).status,413);assert.equal((await batch([event('tool_started',crypto.randomUUID(),{tool:'unlisted'})])).status,400);assert.equal((await batch([event('tool_started',crypto.randomUUID(),{clientAt:new Date(Date.now()-8*86400000).toISOString()})])).status,400);checked('strict schema, version, bytes, batch, origin, cardinality and late-arrival rejection');
 assert.equal((await batch([event('tool_finished',ids[0]!,{outcome:'failure',durationMs:100})])).status,202);const orphan=event('tool_finished',crypto.randomUUID(),{outcome:'success',durationMs:1});assert.equal((await batch([orphan])).status,202);f.set('to',new Date(Date.now()+1000).toISOString());const conflict=await (await http('/api/reports?'+f)).json();assert.equal(conflict.summary.conflicted,1);assert.equal(conflict.missingStarts.count,1);checked('conflicting terminal excluded; terminal-only record remains missing a start');
 const day='day:'+new Date().toISOString().slice(0,10);await db.counter.update({where:{projectId_key:{projectId:p.id,key:day}},data:{count:p.dailyQuota}});assert.equal((await batch([event('tool_started',crypto.randomUUID())])).status,429);await db.counter.update({where:{projectId_key:{projectId:p.id,key:day}},data:{count:21}});const minute='minute:'+Math.floor(Date.now()/60000);await db.counter.upsert({where:{projectId_key:{projectId:p.id,key:minute}},create:{projectId:p.id,key:minute,count:120,expiresAt:new Date(Date.now()+60000)},update:{count:120}});assert.equal((await batch([event('tool_started',crypto.randomUUID())])).status,429);await db.counter.deleteMany({where:{projectId:p.id,key:{startsWith:'minute:'}}});checked('database-backed daily quota and request rate limit enforced');
 const rotated=await (await http('/api/projects/'+p.id,{action:'rotate'})).json();assert.notEqual(rotated.ingestionId,p.ingestionId);assert.equal((await batch(starts)).status,403);qa.ingestionId=rotated.ingestionId;saveQa();assert.equal((await batch(starts,rotated.ingestionId)).status,202);checked('identifier rotation revokes old writes and preserves data');
 const exportRes=await http('/api/reports?'+f+'&export=json');assert.equal(exportRes.status,200);assert.match(exportRes.headers.get('content-disposition')!,/attachment/);checked('authenticated bounded JSON export');
 const doomed=await (await http('/api/projects',{...definition,name:'Disposable deletion test'})).json();assert.equal((await http('/api/projects/'+doomed.id,{action:'delete',confirm:'wrong'})).status,400);assert.equal((await http('/api/projects/'+doomed.id,{action:'delete',confirm:doomed.name})).status,200);assert.equal(await db.project.count({where:{id:doomed.id}}),0);checked('confirmed project deletion and dependent data cascade');
 await db.session.updateMany({where:{userId:(await db.installation.findUniqueOrThrow({where:{id:1}})).ownerId},data:{expiresAt:new Date(0)}});assert.equal((await http('/api/projects')).status,401);checked('expired sessions rejected');
 // Fresh authentication is required; sign-up remains unreachable.
 assert.equal((await http('/api/auth/sign-up/email',{email:'new@test.invalid',password:'this-must-not-create-an-owner',name:'none'},{anon:true})).status,404);checked('public registration disabled');
 await db.rateLimit.deleteMany();for(let i=0;i<5;i++)await http('/api/auth/sign-in/email',{email:qa.email,password:'intentionally-wrong-password'},{anon:true});assert.equal((await http('/api/auth/sign-in/email',{email:qa.email,password:'intentionally-wrong-password'},{anon:true})).status,429);await db.rateLimit.deleteMany();checked('sixth login attempt per minute rejected');
 mkdirSync('work',{recursive:true});writeFileSync('work/integration-results.json',JSON.stringify({checkedAt:new Date().toISOString(),results},null,2));
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>db.$disconnect());
