import './env';import {qa} from './qa-state';import {chromium} from '@playwright/test';import {writeFileSync} from 'node:fs';import assert from 'node:assert/strict';import {PrismaClient} from '@prisma/client';
async function main(){const browser=await chromium.launch({headless:true,args:['--enable-features=WebMCPTesting']});const context=await browser.newContext();const page=await context.newPage();const evidence:Record<string,unknown>={checkedAt:new Date().toISOString(),browser:browser.version(),flags:['--enable-features=WebMCPTesting'],polyfills:false};
try{
 await page.goto('http://localhost:3000/login');await page.getByLabel('Email',{exact:true}).fill(qa.email);await page.getByLabel('Password',{exact:true}).fill(qa.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:'Overview',exact:true}).waitFor({timeout:30000});
 const capabilities=await page.evaluate(()=>{const d=document as any,n=navigator as any;return {documentModelContext:!!d.modelContext,navigatorModelContext:!!n.modelContext,register:typeof d.modelContext?.registerTool,getTools:typeof d.modelContext?.getTools,executeTool:typeof d.modelContext?.executeTool,testing:!!n.modelContextTesting};});evidence.capabilities=capabilities;
 if(capabilities.getTools!=='function'||capabilities.executeTool!=='function'){evidence.status='unverified: tested browser does not expose draft document.modelContext getTools/executeTool';console.log(JSON.stringify(evidence));return;}
 await page.waitForFunction(()=>!!(document as any).modelContext);
 const from=new Date(Date.now()-86400000).toISOString(),to=new Date(Date.now()+10000).toISOString();
 const dashboard=await page.evaluate(async f=>{const m=(document as any).modelContext;const ts=await m.getTools();const names=ts.map((t:any)=>t.name);const metrics=await m.executeTool(ts.find((t:any)=>t.name==='get_tool_metrics'),JSON.stringify(f));const failures=await m.executeTool(ts.find((t:any)=>t.name==='get_tool_failures'),JSON.stringify(f));await m.executeTool(ts.find((t:any)=>t.name==='set_dashboard_filters'),JSON.stringify({...f,source:'manual'}));return {names,metrics,failures};},{projectId:qa.referenceId!,from,to});evidence.dashboard=dashboard;assert.equal(await page.getByRole('combobox',{name:'Execution source',exact:true}).inputValue(),'manual');
 await page.goto('http://localhost:3001');await page.getByLabel('Public ingestion identifier').fill(qa.referenceIngestionId!);await page.getByRole('button',{name:'Connect reference project'}).click();await page.getByRole('status').filter({hasText:'Reference project connected'}).waitFor();
 const run=async(name:string,args:unknown)=>page.evaluate(async({name,args})=>{const m=(document as any).modelContext,tools=await m.getTools();try{return {ok:true,result:await m.executeTool(tools.find((t:any)=>t.name===name),JSON.stringify(args))};}catch(e){return {ok:false,name:e instanceof Error?e.name:'unknown'};}},{name,args});
 evidence.success=await run('search_products',{query:''});await page.getByRole('combobox',{name:'Deterministic scenario'}).selectOption('failure');evidence.failure=await run('check_delivery',{zone:'local'});
 await page.getByRole('combobox',{name:'Deterministic scenario'}).selectOption('cancellation');evidence.cancellation=await page.evaluate(async()=>{const m=(document as any).modelContext,tools=await m.getTools(),ac=new AbortController();const p=m.executeTool(tools.find((t:any)=>t.name==='check_delivery'),JSON.stringify({zone:'local'}),{signal:ac.signal});setTimeout(()=>ac.abort(),50);try{return {resolved:await p};}catch(e){return {rejected:true,name:e instanceof Error?e.name:'unknown'};}});
 await page.getByRole('button',{name:'Flush telemetry'}).click();await page.getByRole('status').filter({hasText:'Flush finished.'}).waitFor();
 const db=new PrismaClient({log:[]});try{
  const events=await db.event.findMany({where:{projectId:qa.referenceId!,source:'webmcp',receivedAt:{gte:new Date(evidence.checkedAt as string)}},select:{kind:true,outcome:true,tool:true,source:true}});
  for(const outcome of ['success','failure','cancellation'])assert.ok(events.some(e=>e.kind==='tool_finished'&&e.outcome===outcome),'Persisted native outcome: '+outcome);
  evidence.persisted={events:events.length,terminalOutcomes:events.filter(e=>e.kind==='tool_finished').map(e=>({tool:e.tool,outcome:e.outcome,source:e.source}))};
 }finally{await db.$disconnect();}
 evidence.status='verified: native draft APIs, visible filter change, and persisted webmcp success/failure/cancellation in flagged Chromium';console.log(JSON.stringify({browser:evidence.browser,capabilities:evidence.capabilities,persisted:evidence.persisted,status:evidence.status}));
}finally{writeFileSync('work/native-results.json',JSON.stringify(evidence,null,2));await browser.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
