import './env';import {PrismaClient} from '@prisma/client';import {spawnSync,spawn} from 'node:child_process';import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';import assert from 'node:assert/strict';import {cleanup} from './retention';
const db=new PrismaClient({log:[]});const log:string[]=[];function pass(s:string){log.push(s);console.log('PASS '+s);}
function docker(args:string[],input?:string){const r=spawnSync('docker',['compose','exec','-T','db',...args],{input,encoding:'utf8',maxBuffer:20*1024*1024});if(r.status!==0)throw Error('Docker database command failed: '+r.stderr);return r.stdout;}
function disposableUrl(name:string){const u=new URL(process.env.DATABASE_URL!);u.pathname='/'+name;return u.toString();}
async function main(){
 const before=await db.event.count();const restart=spawnSync('docker',['compose','restart','db'],{encoding:'utf8'});assert.equal(restart.status,0);for(let n=0;n<30;n++){try{await db.$queryRaw`SELECT 1`;break;}catch{await new Promise(r=>setTimeout(r,1000));}}assert.equal(await db.event.count(),before);pass(`database restart preserved ${before} events`);
 const restore='tally_restore_check',upgrade='tally_upgrade_check';for(const name of [restore,upgrade]){docker(['psql','-U','tally','-d','postgres','-c',`DROP DATABASE IF EXISTS ${name} WITH (FORCE)`]);docker(['createdb','-U','tally',name]);}
 // Stream the binary archive without PowerShell text redirection or any secret in argv.
 await new Promise<void>((resolve,reject)=>{const dump=spawn('docker',['compose','exec','-T','db','pg_dump','-U','tally','-d','tally','-Fc']);const restoreProc=spawn('docker',['compose','exec','-T','db','pg_restore','-U','tally','-d',restore,'--no-owner','--exit-on-error']);dump.stdout.pipe(restoreProc.stdin);let dumpCode:number|null=null;dump.on('exit',c=>{dumpCode=c;});restoreProc.on('exit',c=>{if(c===0&&dumpCode===0)resolve();else reject(Error('Backup/restore failed'));});dump.on('error',reject);restoreProc.on('error',reject);});
 const restored=new PrismaClient({datasourceUrl:disposableUrl(restore),log:[]});assert.equal(await restored.event.count(),before);assert.equal(await restored.project.count(),await db.project.count());assert.equal(await restored.user.count(),await db.user.count());pass('binary backup restored into separate disposable database with matching row counts');
 docker(['psql','-U','tally','-d',upgrade,'-v','ON_ERROR_STOP=1'],readFileSync('prisma/migrations/202609080001_initial/migration.sql','utf8'));
 const old=new PrismaClient({datasourceUrl:disposableUrl(upgrade),log:[]});const uid=crypto.randomUUID();await old.user.create({data:{id:uid,email:'upgrade@fixture.invalid',name:'Upgrade fixture'}});const p=await old.project.create({data:{ownerId:uid,name:'Upgrade fixture',origins:['http://localhost:3001'],tools:['test'],environments:['test'],releases:[],errorCodes:[],routeLabels:[],workflowName:'checkout'}});const id=crypto.randomUUID();for(const kind of ['tool_started','tool_finished'])await old.event.create({data:{projectId:p.id,eventId:crypto.randomUUID(),schemaVersion:1,kind,invocationId:id,tool:'test',environment:'test',source:'manual',clientAt:new Date(Date.now()-40*86400000),...(kind==='tool_finished'?{outcome:'success',durationMs:10}:{})}});
 docker(['psql','-U','tally','-d',upgrade,'-v','ON_ERROR_STOP=1'],readFileSync('prisma/migrations/202609080002_retention_index/migration.sql','utf8'));assert.equal(await old.event.count(),2);const indices=await old.$queryRaw<{indexname:string}[]>`SELECT indexname FROM pg_indexes WHERE indexname='Event_projectId_kind_clientAt_idx'`;assert.equal(indices.length,1);pass('additive upgrade from initial schema preserved representative existing project and invocation');
 await old.event.create({data:{projectId:p.id,eventId:crypto.randomUUID(),schemaVersion:1,kind:'tool_finished',invocationId:id,tool:'test',environment:'test',source:'manual',clientAt:new Date(),outcome:'success',durationMs:10}});assert.equal(await cleanup(old),3);assert.equal(await old.event.count(),0);pass('retention removes complete expired invocation, including recent duplicate terminal, leaving no derived data');
 await old.$disconnect();await restored.$disconnect();for(const name of [restore,upgrade])docker(['dropdb','-U','tally',name]);pass('disposable restore and upgrade databases removed');mkdirSync('work',{recursive:true});writeFileSync('work/operations-results.json',JSON.stringify({checkedAt:new Date().toISOString(),results:log},null,2));
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>db.$disconnect());
