import './env';import {qa} from './qa-state';import {PrismaClient} from '@prisma/client';import {writeFileSync} from 'node:fs';import assert from 'node:assert/strict';import {cpus,totalmem,platform,release} from 'node:os';
const db=new PrismaClient({log:[]});const base='http://localhost:3000';
async function main(){await db.rateLimit.deleteMany();const l=await fetch(base+'/api/auth/sign-in/email',{method:'POST',headers:{'Content-Type':'application/json',Origin:base},body:JSON.stringify({email:qa.email,password:qa.password})});assert.equal(l.status,200);const cookie=l.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ');const post=async(path:string,b:unknown)=>fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json',Origin:base,Cookie:cookie},body:JSON.stringify(b)});
 const r=await post('/api/projects',{name:'Performance workload',origins:['http://localhost:3001'],tools:['test'],environments:['performance'],releases:['v1'],errorCodes:[],routeLabels:[],workflowName:'checkout',retentionDays:30,dailyQuota:100000});assert.equal(r.status,201);const p=await r.json();const batches:unknown[][]=[];for(let b=0;b<100;b++){const es=[];for(let i=0;i<25;i++){const id=crypto.randomUUID();const common={schemaVersion:1,invocationId:id,tool:'test',environment:'performance',release:'v1',source:'manual',clientAt:new Date().toISOString()};es.push({...common,eventId:crypto.randomUUID(),kind:'tool_started'},{...common,eventId:crypto.randomUUID(),kind:'tool_finished',outcome:(i%5===0?'failure':'success'),durationMs:100+i*10});}batches.push(es);}
 const elapsed:number[]=[];const start=performance.now();for(let i=0;i<batches.length;i+=5)await Promise.all(batches.slice(i,i+5).map(async events=>{const s=performance.now();const res=await fetch(base+'/api/v1/events',{method:'POST',headers:{'Content-Type':'application/json',Origin:'http://localhost:3001'},body:JSON.stringify({ingestionId:p.ingestionId,events})});assert.equal(res.status,202);elapsed.push(performance.now()-s);}));const ingestionMs=performance.now()-start;
 const q=new URLSearchParams({projectId:p.id,from:new Date(Date.now()-86400000).toISOString(),to:new Date(Date.now()+1000).toISOString()});const reports:number[]=[];for(let i=0;i<10;i++){const s=performance.now();const res=await fetch(base+'/api/reports?'+q,{headers:{Cookie:cookie}});assert.equal(res.status,200);const data=await res.json();assert.equal(data.summary.callsStarted,2500);assert.equal(data.summary.successRate,.8);reports.push(performance.now()-s);}
 const stats=(a:number[])=>{a.sort((a,b)=>a-b);return {medianMs:Math.round((a[(a.length-1)>>1]!+a[a.length>>1]!)/2),p95Ms:Math.round(a[Math.ceil(a.length*.95)-1]!),maxMs:Math.round(a.at(-1)!)};};const evidence={checkedAt:new Date().toISOString(),environment:{os:platform()+' '+release(),node:process.version,cpu:cpus()[0]?.model,logicalCpus:cpus().length,hostMemoryGiB:Math.round(totalmem()/2**30),database:'PostgreSQL 17.9 Docker, 768MiB limit',application:'Next.js production server, localhost'},workload:{events:5000,invocations:2500,batchSize:50,concurrency:5,requests:100,reportQueries:10},ingestion:{totalMs:Math.round(ingestionMs),eventsPerSecond:Math.round(5000000/ingestionMs),...stats(elapsed)},reports:stats(reports),limits:'One local workload; not a scalability guarantee. Current report service rejects projects above 50,000 retained events.'};writeFileSync('docs/PERFORMANCE.json',JSON.stringify(evidence,null,2));console.log(JSON.stringify(evidence,null,2));assert.equal((await post('/api/projects/'+p.id,{action:'delete',confirm:p.name})).status,200);
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>db.$disconnect());
